# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import json
import warnings
import pulumi
import pulumi.runtime
from typing import Union
from .. import utilities, tables

class Subnet(pulumi.CustomResource):
    availability_zone: pulumi.Output[str]
    """
    The availability zone within which the subnet should be created.
    """
    available_ip_count: pulumi.Output[float]
    """
    The number of available IPs.
    """
    cidr_block: pulumi.Output[str]
    """
    A network address block of the subnet.
    """
    create_time: pulumi.Output[str]
    """
    Creation time of subnet resource.
    """
    is_default: pulumi.Output[bool]
    """
    Indicates whether it is the default VPC for this region.
    """
    is_multicast: pulumi.Output[bool]
    """
    Indicates whether multicast is enabled. The default value is 'true'.
    """
    name: pulumi.Output[str]
    """
    The name of subnet to be created.
    """
    route_table_id: pulumi.Output[str]
    """
    ID of a routing table to which the subnet should be associated.
    """
    tags: pulumi.Output[dict]
    """
    Tags of the subnet.
    """
    vpc_id: pulumi.Output[str]
    """
    ID of the VPC to be associated.
    """
    def __init__(__self__, resource_name, opts=None, availability_zone=None, cidr_block=None, is_multicast=None, name=None, route_table_id=None, tags=None, vpc_id=None, __props__=None, __name__=None, __opts__=None):
        """
        Provide a resource to create a VPC subnet.
        
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] availability_zone: The availability zone within which the subnet should be created.
        :param pulumi.Input[str] cidr_block: A network address block of the subnet.
        :param pulumi.Input[bool] is_multicast: Indicates whether multicast is enabled. The default value is 'true'.
        :param pulumi.Input[str] name: The name of subnet to be created.
        :param pulumi.Input[str] route_table_id: ID of a routing table to which the subnet should be associated.
        :param pulumi.Input[dict] tags: Tags of the subnet.
        :param pulumi.Input[str] vpc_id: ID of the VPC to be associated.

        > This content is derived from https://github.com/terraform-providers/terraform-provider-tencentcloud/blob/master/website/docs/r/subnet.html.markdown.
        """
        if __name__ is not None:
            warnings.warn("explicit use of __name__ is deprecated", DeprecationWarning)
            resource_name = __name__
        if __opts__ is not None:
            warnings.warn("explicit use of __opts__ is deprecated, use 'opts' instead", DeprecationWarning)
            opts = __opts__
        if opts is None:
            opts = pulumi.ResourceOptions()
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.version is None:
            opts.version = utilities.get_version()
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = dict()

            if availability_zone is None:
                raise TypeError("Missing required property 'availability_zone'")
            __props__['availability_zone'] = availability_zone
            if cidr_block is None:
                raise TypeError("Missing required property 'cidr_block'")
            __props__['cidr_block'] = cidr_block
            __props__['is_multicast'] = is_multicast
            __props__['name'] = name
            __props__['route_table_id'] = route_table_id
            __props__['tags'] = tags
            if vpc_id is None:
                raise TypeError("Missing required property 'vpc_id'")
            __props__['vpc_id'] = vpc_id
            __props__['available_ip_count'] = None
            __props__['create_time'] = None
            __props__['is_default'] = None
        super(Subnet, __self__).__init__(
            'tencentcloud:tencentcloud_vpc/subnet:Subnet',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name, id, opts=None, availability_zone=None, available_ip_count=None, cidr_block=None, create_time=None, is_default=None, is_multicast=None, name=None, route_table_id=None, tags=None, vpc_id=None):
        """
        Get an existing Subnet resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.
        
        :param str resource_name: The unique name of the resulting resource.
        :param str id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] availability_zone: The availability zone within which the subnet should be created.
        :param pulumi.Input[float] available_ip_count: The number of available IPs.
        :param pulumi.Input[str] cidr_block: A network address block of the subnet.
        :param pulumi.Input[str] create_time: Creation time of subnet resource.
        :param pulumi.Input[bool] is_default: Indicates whether it is the default VPC for this region.
        :param pulumi.Input[bool] is_multicast: Indicates whether multicast is enabled. The default value is 'true'.
        :param pulumi.Input[str] name: The name of subnet to be created.
        :param pulumi.Input[str] route_table_id: ID of a routing table to which the subnet should be associated.
        :param pulumi.Input[dict] tags: Tags of the subnet.
        :param pulumi.Input[str] vpc_id: ID of the VPC to be associated.

        > This content is derived from https://github.com/terraform-providers/terraform-provider-tencentcloud/blob/master/website/docs/r/subnet.html.markdown.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = dict()
        __props__["availability_zone"] = availability_zone
        __props__["available_ip_count"] = available_ip_count
        __props__["cidr_block"] = cidr_block
        __props__["create_time"] = create_time
        __props__["is_default"] = is_default
        __props__["is_multicast"] = is_multicast
        __props__["name"] = name
        __props__["route_table_id"] = route_table_id
        __props__["tags"] = tags
        __props__["vpc_id"] = vpc_id
        return Subnet(resource_name, opts=opts, __props__=__props__)
    def translate_output_property(self, prop):
        return tables._CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop

    def translate_input_property(self, prop):
        return tables._SNAKE_TO_CAMEL_CASE_TABLE.get(prop) or prop

