# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import json
import warnings
import pulumi
import pulumi.runtime
from typing import Union
from .. import utilities, tables

__config__ = pulumi.Config('tencentcloud')

assume_role = __config__.get('assumeRole')
"""
The `assume_role` block. If provided, terraform will attempt to assume this role using the supplied credentials.
"""

domain = __config__.get('domain')
"""
The root domain of the API request, Default is `tencentcloudapi.com`.
"""

protocol = __config__.get('protocol')
"""
The protocol of the API request. Valid values: `HTTP` and `HTTPS`. Default is `HTTPS`.
"""

region = __config__.get('region') or utilities.get_env('TENCENTCLOUD_REGION', 'TENCENTCLOUD_DEFAULT_REGION')
"""
This is the TencentCloud region. It must be provided, but it can also be sourced from the `TENCENTCLOUD_REGION`
environment variables. The default input value is ap-guangzhou.
"""

secret_id = __config__.get('secretId') or utilities.get_env('TENCENTCLOUD_SECRET_ID', 'tencentcloud_secret_id')
"""
This is the TencentCloud access key. It must be provided, but it can also be sourced from the `TENCENTCLOUD_SECRET_ID`
environment variable.
"""

secret_key = __config__.get('secretKey') or utilities.get_env('TENCENTCLOUD_SECRET_KEY', 'tencentcloud_secret_key')
"""
This is the TencentCloud secret key. It must be provided, but it can also be sourced from the `TENCENTCLOUD_SECRET_KEY`
environment variable.
"""

security_token = __config__.get('securityToken')
"""
TencentCloud Security Token of temporary access credentials. It can be sourced from the `TENCENTCLOUD_SECURITY_TOKEN`
environment variable. Notice: for supported products, please refer to: [temporary key supported
products](https://intl.cloud.tencent.com/document/product/598/10588).
"""

