# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

_SNAKE_TO_CAMEL_CASE_TABLE = {
    "assume_role": "assumeRole",
    "availability_zone": "availabilityZone",
    "available_ip_count": "availableIpCount",
    "cidr_block": "cidrBlock",
    "create_time": "createTime",
    "dns_servers": "dnsServers",
    "is_default": "isDefault",
    "is_multicast": "isMulticast",
    "route_table_id": "routeTableId",
    "secret_id": "secretId",
    "secret_key": "secretKey",
    "security_token": "securityToken",
    "vpc_id": "vpcId",
}

_CAMEL_TO_SNAKE_CASE_TABLE = {
    "assumeRole": "assume_role",
    "availabilityZone": "availability_zone",
    "availableIpCount": "available_ip_count",
    "cidrBlock": "cidr_block",
    "createTime": "create_time",
    "dnsServers": "dns_servers",
    "isDefault": "is_default",
    "isMulticast": "is_multicast",
    "routeTableId": "route_table_id",
    "secretId": "secret_id",
    "secretKey": "secret_key",
    "securityToken": "security_token",
    "vpcId": "vpc_id",
}
